# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'amp-ssi-google-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amp-ssi-google-ios
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
