# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'amplify-ios-sign-in-proto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amplify-ios-sign-in-proto
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
