# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'remote-image-proto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for remote-image-proto
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
