# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'amplify-datastore-storage-proto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'

  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
