# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'existing-bucket-proto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for existing-bucket-proto
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
