# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'realtime-chat-proto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realtime-chat-proto
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
end
